[2021-12-01 20:41:17,759: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-01 20:41:17,770: INFO/MainProcess] mingle: searching for neighbors
[2021-12-01 20:41:18,787: INFO/MainProcess] mingle: all alone
[2021-12-01 20:41:18,797: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-12-01 20:41:18,797: INFO/MainProcess] celery@7703b9bd351d ready.
[2021-12-01 20:41:19,247: INFO/Beat] beat: Starting...
[2021-12-01 20:41:19,268: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:41:19,276: INFO/MainProcess] Received task: offer.tasks.req[bf3eb8fd-39b1-48d5-b1dd-68f706ba4029]  
[2021-12-01 20:41:19,292: INFO/ForkPoolWorker-8] Task offer.tasks.req[bf3eb8fd-39b1-48d5-b1dd-68f706ba4029] succeeded in 0.014202753001882229s: None
[2021-12-01 20:41:22,772: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-01 20:42:00,030: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:42:00,040: INFO/MainProcess] Received task: offer.tasks.req[4248fb5d-52ca-4233-a2d3-12baa65b8e06]  
[2021-12-01 20:42:00,086: INFO/ForkPoolWorker-8] Task offer.tasks.req[4248fb5d-52ca-4233-a2d3-12baa65b8e06] succeeded in 0.04121487000156776s: None
[2021-12-01 20:42:14,016: INFO/MainProcess] beat: Shutting down...
[2021-12-01 20:42:27,445: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-01 20:42:27,456: INFO/MainProcess] mingle: searching for neighbors
[2021-12-01 20:42:28,482: INFO/MainProcess] mingle: all alone
[2021-12-01 20:42:28,492: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-12-01 20:42:28,492: INFO/MainProcess] celery@ebf8fc721161 ready.
[2021-12-01 20:42:28,839: INFO/Beat] beat: Starting...
[2021-12-01 20:42:32,450: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-01 20:43:00,085: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:43:00,119: INFO/MainProcess] Received task: offer.tasks.req[edd0d6bb-61fb-4e33-b8fe-d7c5dc770f96]  
[2021-12-01 20:43:00,189: INFO/ForkPoolWorker-8] Task offer.tasks.req[edd0d6bb-61fb-4e33-b8fe-d7c5dc770f96] succeeded in 0.06340941699818359s: None
[2021-12-01 20:44:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:44:00,056: INFO/MainProcess] Received task: offer.tasks.req[b8197d67-1c59-4e5c-af31-54413eb0c571]  
[2021-12-01 20:44:00,097: INFO/ForkPoolWorker-8] Task offer.tasks.req[b8197d67-1c59-4e5c-af31-54413eb0c571] succeeded in 0.03850748300101259s: None
[2021-12-01 20:45:00,051: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:45:00,056: INFO/MainProcess] Received task: offer.tasks.req[ab027e36-babb-4bdc-8538-f0eedfa42438]  
[2021-12-01 20:45:00,098: INFO/ForkPoolWorker-8] Task offer.tasks.req[ab027e36-babb-4bdc-8538-f0eedfa42438] succeeded in 0.03918124900155817s: None
[2021-12-01 20:45:30,607: INFO/MainProcess] beat: Shutting down...
[2021-12-01 20:45:49,898: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-01 20:45:49,909: INFO/MainProcess] mingle: searching for neighbors
[2021-12-01 20:45:50,939: INFO/MainProcess] mingle: all alone
[2021-12-01 20:45:50,958: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-12-01 20:45:50,958: INFO/MainProcess] celery@39a9d9b173a7 ready.
[2021-12-01 20:45:51,622: INFO/Beat] beat: Starting...
[2021-12-01 20:45:55,161: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-01 20:46:00,035: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:46:00,049: INFO/MainProcess] Received task: offer.tasks.req[2307a452-9d28-4292-9665-6416ec8ac8f0]  
[2021-12-01 20:46:00,091: INFO/ForkPoolWorker-7] Task offer.tasks.req[2307a452-9d28-4292-9665-6416ec8ac8f0] succeeded in 0.039660942002228694s: None
[2021-12-01 20:47:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:47:00,058: INFO/MainProcess] Received task: offer.tasks.req[69cac819-8cb9-491c-8f42-dc5c3563b3c2]  
[2021-12-01 20:47:00,136: INFO/ForkPoolWorker-7] Task offer.tasks.req[69cac819-8cb9-491c-8f42-dc5c3563b3c2] succeeded in 0.07408545600264915s: None
[2021-12-01 20:48:00,049: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:48:00,056: INFO/MainProcess] Received task: offer.tasks.req[d42114bf-67d2-43d7-9b0b-c3e67518ef1f]  
[2021-12-01 20:48:00,103: INFO/ForkPoolWorker-7] Task offer.tasks.req[d42114bf-67d2-43d7-9b0b-c3e67518ef1f] succeeded in 0.04416102600225713s: None
[2021-12-01 20:49:00,052: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:49:00,055: INFO/MainProcess] Received task: offer.tasks.req[c15e57d4-e32d-424d-9392-406c574558de]  
[2021-12-01 20:49:00,090: INFO/ForkPoolWorker-7] Task offer.tasks.req[c15e57d4-e32d-424d-9392-406c574558de] succeeded in 0.03272615800233325s: None
[2021-12-01 20:50:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:50:00,058: INFO/MainProcess] Received task: offer.tasks.req[d7c94c5b-ee34-479e-845d-e3a8cfa7c87d]  
[2021-12-01 20:50:00,099: INFO/ForkPoolWorker-7] Task offer.tasks.req[d7c94c5b-ee34-479e-845d-e3a8cfa7c87d] succeeded in 0.03941476899854024s: None
[2021-12-01 20:51:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:51:00,060: INFO/MainProcess] Received task: offer.tasks.req[75650413-072b-487a-84ab-40421ed9103f]  
[2021-12-01 20:51:00,127: INFO/ForkPoolWorker-7] Task offer.tasks.req[75650413-072b-487a-84ab-40421ed9103f] succeeded in 0.06245649199991021s: None
[2021-12-01 20:51:07,625: INFO/MainProcess] beat: Shutting down...
[2021-12-01 20:51:29,661: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-01 20:51:29,680: INFO/MainProcess] mingle: searching for neighbors
[2021-12-01 20:51:30,704: INFO/MainProcess] mingle: all alone
[2021-12-01 20:51:30,715: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-12-01 20:51:30,715: INFO/MainProcess] celery@cd7972e7f2e2 ready.
[2021-12-01 20:51:31,442: INFO/Beat] beat: Starting...
[2021-12-01 20:51:34,775: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-01 20:52:00,052: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:52:00,067: INFO/MainProcess] Received task: offer.tasks.req[f7137900-5f20-4846-94d4-b310748f4d13]  
[2021-12-01 20:52:00,112: INFO/ForkPoolWorker-8] Task offer.tasks.req[f7137900-5f20-4846-94d4-b310748f4d13] succeeded in 0.04158960600034334s: None
[2021-12-01 20:53:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:53:00,053: INFO/MainProcess] Received task: offer.tasks.req[2864f680-43f5-4429-a1a0-ca221ea92584]  
[2021-12-01 20:53:00,092: INFO/ForkPoolWorker-8] Task offer.tasks.req[2864f680-43f5-4429-a1a0-ca221ea92584] succeeded in 0.03661069500230951s: None
[2021-12-01 20:54:00,049: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:54:00,054: INFO/MainProcess] Received task: offer.tasks.req[7e7e68a9-a0f3-4897-8e41-9d43d0c89658]  
[2021-12-01 20:54:00,095: INFO/ForkPoolWorker-8] Task offer.tasks.req[7e7e68a9-a0f3-4897-8e41-9d43d0c89658] succeeded in 0.03976583600160666s: None
[2021-12-01 20:55:00,058: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:55:00,066: INFO/MainProcess] Received task: offer.tasks.req[480dddf7-b8a3-4e24-b306-0e05659e065f]  
[2021-12-01 20:55:00,115: INFO/ForkPoolWorker-8] Task offer.tasks.req[480dddf7-b8a3-4e24-b306-0e05659e065f] succeeded in 0.04633026000010432s: None
[2021-12-01 20:56:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-01 20:56:00,056: INFO/MainProcess] Received task: offer.tasks.req[07481cb8-bfaa-4e7e-83ef-ababc6f8a052]  
[2021-12-01 20:56:00,105: INFO/ForkPoolWorker-8] Task offer.tasks.req[07481cb8-bfaa-4e7e-83ef-ababc6f8a052] succeeded in 0.04519536499719834s: None
[2021-12-01 20:56:34,306: INFO/MainProcess] beat: Shutting down...
[2021-12-02 07:13:52,711: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-02 07:13:52,721: INFO/MainProcess] mingle: searching for neighbors
[2021-12-02 07:13:53,744: INFO/MainProcess] mingle: all alone
[2021-12-02 07:13:53,754: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-12-02 07:13:53,754: INFO/MainProcess] celery@185865a0fc18 ready.
[2021-12-02 07:13:53,971: INFO/Beat] beat: Starting...
[2021-12-02 07:13:53,990: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:13:53,998: INFO/MainProcess] Received task: offer.tasks.req[eeeb8892-8457-43ad-b87f-6e37340f6144]  
[2021-12-02 07:13:54,007: ERROR/ForkPoolWorker-8] Task offer.tasks.req[eeeb8892-8457-43ad-b87f-6e37340f6144] raised unexpected: OperationalError('could not connect to server: Connection refused\n\tIs the server running on host "db" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/offer/tasks.py", line 11, in req
    for buyer in buyers:
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

[2021-12-02 07:13:57,830: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-02 07:14:00,000: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:14:00,005: INFO/MainProcess] Received task: offer.tasks.req[9b01d3ca-fc05-4750-bdf1-ef99d078749c]  
[2021-12-02 07:14:00,017: ERROR/ForkPoolWorker-8] Task offer.tasks.req[9b01d3ca-fc05-4750-bdf1-ef99d078749c] raised unexpected: OperationalError('could not connect to server: Connection refused\n\tIs the server running on host "db" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/offer/tasks.py", line 11, in req
    for buyer in buyers:
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

[2021-12-02 07:14:45,484: INFO/MainProcess] beat: Shutting down...
[2021-12-02 07:14:51,619: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-02 07:14:51,625: INFO/MainProcess] mingle: searching for neighbors
[2021-12-02 07:14:52,633: INFO/Beat] beat: Starting...
[2021-12-02 07:14:52,638: INFO/MainProcess] mingle: all alone
[2021-12-02 07:14:52,647: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-12-02 07:14:52,647: INFO/MainProcess] celery@3d156825a5c8 ready.
[2021-12-02 07:14:57,016: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-02 07:15:00,031: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:15:00,069: INFO/MainProcess] Received task: offer.tasks.req[ef5da967-a724-4401-b511-6c453217bff8]  
[2021-12-02 07:15:00,123: INFO/ForkPoolWorker-8] Task offer.tasks.req[ef5da967-a724-4401-b511-6c453217bff8] succeeded in 0.048450588000008565s: None
[2021-12-02 07:16:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:16:00,053: INFO/MainProcess] Received task: offer.tasks.req[365151ff-5329-4f12-b3c9-e8a3a77359fb]  
[2021-12-02 07:16:00,065: INFO/ForkPoolWorker-8] Task offer.tasks.req[365151ff-5329-4f12-b3c9-e8a3a77359fb] succeeded in 0.009683155000004717s: None
[2021-12-02 07:17:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:17:00,056: INFO/MainProcess] Received task: offer.tasks.req[11ee099c-e951-4d6a-8743-06a3719ee583]  
[2021-12-02 07:17:00,080: INFO/ForkPoolWorker-8] Task offer.tasks.req[11ee099c-e951-4d6a-8743-06a3719ee583] succeeded in 0.020749686999977257s: None
[2021-12-02 07:18:00,033: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:18:00,035: INFO/MainProcess] Received task: offer.tasks.req[2ee645e7-72e7-49f5-81f8-be3dc9d5e0af]  
[2021-12-02 07:18:00,043: INFO/ForkPoolWorker-8] Task offer.tasks.req[2ee645e7-72e7-49f5-81f8-be3dc9d5e0af] succeeded in 0.0069377809999764395s: None
[2021-12-02 07:19:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:19:00,056: INFO/MainProcess] Received task: offer.tasks.req[82ec3b3f-c707-405a-8273-c62fdc097f08]  
[2021-12-02 07:19:00,079: INFO/ForkPoolWorker-8] Task offer.tasks.req[82ec3b3f-c707-405a-8273-c62fdc097f08] succeeded in 0.02038362500002222s: None
[2021-12-02 07:20:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:20:00,053: INFO/MainProcess] Received task: offer.tasks.req[88e7f5e4-1298-46db-bc05-b51323baf4dd]  
[2021-12-02 07:20:00,060: INFO/ForkPoolWorker-8] Task offer.tasks.req[88e7f5e4-1298-46db-bc05-b51323baf4dd] succeeded in 0.006735066999965511s: None
[2021-12-02 07:21:00,051: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:21:00,056: INFO/MainProcess] Received task: offer.tasks.req[7ad0b3c8-d717-4862-9906-86b7bd400dd5]  
[2021-12-02 07:21:00,078: INFO/ForkPoolWorker-8] Task offer.tasks.req[7ad0b3c8-d717-4862-9906-86b7bd400dd5] succeeded in 0.019490771999926437s: None
[2021-12-02 07:22:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:22:00,052: INFO/MainProcess] Received task: offer.tasks.req[3427e875-fcc1-4a14-80e9-7d940e5c7d29]  
[2021-12-02 07:22:00,060: INFO/ForkPoolWorker-8] Task offer.tasks.req[3427e875-fcc1-4a14-80e9-7d940e5c7d29] succeeded in 0.006912821000014446s: None
[2021-12-02 07:23:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:23:00,056: INFO/MainProcess] Received task: offer.tasks.req[0c0b3501-ef7c-442a-993c-a560b0bb0d0b]  
[2021-12-02 07:23:00,079: INFO/ForkPoolWorker-8] Task offer.tasks.req[0c0b3501-ef7c-442a-993c-a560b0bb0d0b] succeeded in 0.020576341000037246s: None
[2021-12-02 07:24:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:24:00,056: INFO/MainProcess] Received task: offer.tasks.req[500eda13-5807-4500-84ec-dc62ff1477db]  
[2021-12-02 07:24:00,079: INFO/ForkPoolWorker-8] Task offer.tasks.req[500eda13-5807-4500-84ec-dc62ff1477db] succeeded in 0.019743628000014724s: None
[2021-12-02 07:25:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:25:00,052: INFO/MainProcess] Received task: offer.tasks.req[5b654a3e-5418-41cc-b5aa-5fd835ea7a57]  
[2021-12-02 07:25:00,060: INFO/ForkPoolWorker-8] Task offer.tasks.req[5b654a3e-5418-41cc-b5aa-5fd835ea7a57] succeeded in 0.007391718999997465s: None
[2021-12-02 07:26:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:26:00,056: INFO/MainProcess] Received task: offer.tasks.req[454a04b3-589b-4a3e-93ca-280b6feb57ed]  
[2021-12-02 07:26:00,081: INFO/ForkPoolWorker-8] Task offer.tasks.req[454a04b3-589b-4a3e-93ca-280b6feb57ed] succeeded in 0.021606602000019848s: None
[2021-12-02 07:27:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:27:00,056: INFO/MainProcess] Received task: offer.tasks.req[e0c3ac3e-c83b-4f44-83e0-75e6214b7962]  
[2021-12-02 07:27:00,079: INFO/ForkPoolWorker-8] Task offer.tasks.req[e0c3ac3e-c83b-4f44-83e0-75e6214b7962] succeeded in 0.01987409299999854s: None
[2021-12-02 07:28:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:28:00,052: INFO/MainProcess] Received task: offer.tasks.req[c1f6b28e-2af9-4101-a638-0df03c545f8d]  
[2021-12-02 07:28:00,062: INFO/ForkPoolWorker-8] Task offer.tasks.req[c1f6b28e-2af9-4101-a638-0df03c545f8d] succeeded in 0.008580586999983097s: None
[2021-12-02 07:29:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:29:00,052: INFO/MainProcess] Received task: offer.tasks.req[9ed8d09c-7a65-4cff-bd9c-965207c4691d]  
[2021-12-02 07:29:00,060: INFO/ForkPoolWorker-8] Task offer.tasks.req[9ed8d09c-7a65-4cff-bd9c-965207c4691d] succeeded in 0.006979939000075319s: None
[2021-12-02 07:30:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:30:00,055: INFO/MainProcess] Received task: offer.tasks.req[6e76a9a4-6745-47bf-b9ed-a7357f0f45c9]  
[2021-12-02 07:30:00,079: INFO/ForkPoolWorker-8] Task offer.tasks.req[6e76a9a4-6745-47bf-b9ed-a7357f0f45c9] succeeded in 0.02035833799982356s: None
[2021-12-02 07:31:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:31:00,056: INFO/MainProcess] Received task: offer.tasks.req[4a41bf69-dbc7-4665-afba-6979df19c7c0]  
[2021-12-02 07:31:00,078: INFO/ForkPoolWorker-8] Task offer.tasks.req[4a41bf69-dbc7-4665-afba-6979df19c7c0] succeeded in 0.019003126999905362s: None
[2021-12-02 07:32:00,004: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:32:00,010: INFO/MainProcess] Received task: offer.tasks.req[0e0860e8-4d55-47ae-a689-293a1cbc8aa8]  
[2021-12-02 07:32:00,040: INFO/ForkPoolWorker-8] Task offer.tasks.req[0e0860e8-4d55-47ae-a689-293a1cbc8aa8] succeeded in 0.027231560000018362s: None
[2021-12-02 07:33:00,032: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:33:00,037: INFO/MainProcess] Received task: offer.tasks.req[dc20b019-dd94-4c60-aeb7-559fcb81c04e]  
[2021-12-02 07:33:00,073: INFO/ForkPoolWorker-8] Task offer.tasks.req[dc20b019-dd94-4c60-aeb7-559fcb81c04e] succeeded in 0.03291223900009754s: None
[2021-12-02 07:34:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:34:00,055: INFO/MainProcess] Received task: offer.tasks.req[2b98e3ae-9bf9-4037-a585-cd4dc7739dd2]  
[2021-12-02 07:34:00,086: INFO/ForkPoolWorker-8] Task offer.tasks.req[2b98e3ae-9bf9-4037-a585-cd4dc7739dd2] succeeded in 0.027076657999941744s: None
[2021-12-02 07:35:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:35:00,052: INFO/MainProcess] Received task: offer.tasks.req[549dff87-94ef-4da0-ba9c-19ee90799234]  
[2021-12-02 07:35:00,086: INFO/ForkPoolWorker-8] Task offer.tasks.req[549dff87-94ef-4da0-ba9c-19ee90799234] succeeded in 0.033409874999961175s: None
[2021-12-02 07:36:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:36:00,052: INFO/MainProcess] Received task: offer.tasks.req[584a8937-3c01-40ef-bd4e-484b93dde0cd]  
[2021-12-02 07:36:00,061: INFO/ForkPoolWorker-8] Task offer.tasks.req[584a8937-3c01-40ef-bd4e-484b93dde0cd] succeeded in 0.007140099999787708s: None
[2021-12-02 07:37:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:37:00,056: INFO/MainProcess] Received task: offer.tasks.req[c37ce78d-3b3c-4207-8e22-e82ad9eec432]  
[2021-12-02 07:37:00,079: INFO/ForkPoolWorker-8] Task offer.tasks.req[c37ce78d-3b3c-4207-8e22-e82ad9eec432] succeeded in 0.020419267000079344s: None
[2021-12-02 07:38:00,051: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:38:00,056: INFO/MainProcess] Received task: offer.tasks.req[8261e1f2-244f-4534-92cb-5d6188e3941e]  
[2021-12-02 07:38:00,093: INFO/ForkPoolWorker-8] Task offer.tasks.req[8261e1f2-244f-4534-92cb-5d6188e3941e] succeeded in 0.03417543699993075s: None
[2021-12-02 07:39:00,015: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:39:00,020: INFO/MainProcess] Received task: offer.tasks.req[132eeccf-b2d7-4b0b-adb3-b6903b395537]  
[2021-12-02 07:39:00,094: INFO/ForkPoolWorker-8] Task offer.tasks.req[132eeccf-b2d7-4b0b-adb3-b6903b395537] succeeded in 0.07141463199991449s: None
[2021-12-02 07:40:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:40:00,055: INFO/MainProcess] Received task: offer.tasks.req[2e269ffd-5978-4727-995b-4fe2411d9d17]  
[2021-12-02 07:40:00,079: INFO/ForkPoolWorker-8] Task offer.tasks.req[2e269ffd-5978-4727-995b-4fe2411d9d17] succeeded in 0.020768137000004572s: None
[2021-12-02 07:41:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:41:00,052: INFO/MainProcess] Received task: offer.tasks.req[e214af2e-ba83-4dca-bb02-b1e17fca61db]  
[2021-12-02 07:41:00,060: INFO/ForkPoolWorker-8] Task offer.tasks.req[e214af2e-ba83-4dca-bb02-b1e17fca61db] succeeded in 0.006862546000093062s: None
[2021-12-02 07:42:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:42:00,055: INFO/MainProcess] Received task: offer.tasks.req[c7fc991a-4f7c-48b2-8de1-cf150f0b2283]  
[2021-12-02 07:42:00,093: INFO/ForkPoolWorker-8] Task offer.tasks.req[c7fc991a-4f7c-48b2-8de1-cf150f0b2283] succeeded in 0.03448998399994707s: None
[2021-12-02 07:43:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:43:00,055: INFO/MainProcess] Received task: offer.tasks.req[75f9a03a-59c1-47c2-8607-1596dfc071ef]  
[2021-12-02 07:43:00,118: INFO/ForkPoolWorker-8] Task offer.tasks.req[75f9a03a-59c1-47c2-8607-1596dfc071ef] succeeded in 0.05949319399996966s: None
[2021-12-02 07:44:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:44:00,055: INFO/MainProcess] Received task: offer.tasks.req[b9cc2f27-98f2-4ba7-915f-f2d187b5adc1]  
[2021-12-02 07:44:00,079: INFO/ForkPoolWorker-8] Task offer.tasks.req[b9cc2f27-98f2-4ba7-915f-f2d187b5adc1] succeeded in 0.020857986000009987s: None
[2021-12-02 07:45:00,006: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:45:00,011: INFO/MainProcess] Received task: offer.tasks.req[e434bca2-4a87-453e-a233-19d5ca35866d]  
[2021-12-02 07:45:00,033: INFO/ForkPoolWorker-8] Task offer.tasks.req[e434bca2-4a87-453e-a233-19d5ca35866d] succeeded in 0.019230461999995896s: None
[2021-12-02 07:46:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:46:00,056: INFO/MainProcess] Received task: offer.tasks.req[23560eb4-8581-477c-95a5-257267428bb6]  
[2021-12-02 07:46:00,082: INFO/ForkPoolWorker-8] Task offer.tasks.req[23560eb4-8581-477c-95a5-257267428bb6] succeeded in 0.022611972000049718s: None
[2021-12-02 07:47:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:47:00,052: INFO/MainProcess] Received task: offer.tasks.req[088b47f3-af55-4c87-a86a-7add9d800876]  
[2021-12-02 07:47:00,061: INFO/ForkPoolWorker-8] Task offer.tasks.req[088b47f3-af55-4c87-a86a-7add9d800876] succeeded in 0.007669093999993493s: None
[2021-12-02 07:48:00,025: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:48:00,030: INFO/MainProcess] Received task: offer.tasks.req[6b97a2f1-5a31-4411-b294-b94852b27e2f]  
[2021-12-02 07:48:00,053: INFO/ForkPoolWorker-8] Task offer.tasks.req[6b97a2f1-5a31-4411-b294-b94852b27e2f] succeeded in 0.02030078500001764s: None
[2021-12-02 07:49:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:49:00,052: INFO/MainProcess] Received task: offer.tasks.req[a8bfbea5-b78d-4a6f-9a35-c41f78f3967b]  
[2021-12-02 07:49:00,060: INFO/ForkPoolWorker-8] Task offer.tasks.req[a8bfbea5-b78d-4a6f-9a35-c41f78f3967b] succeeded in 0.007002741000178503s: None
[2021-12-02 07:50:00,050: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:50:00,055: INFO/MainProcess] Received task: offer.tasks.req[8d93b335-f5c8-495e-8865-890f971a73fc]  
[2021-12-02 07:50:00,077: INFO/ForkPoolWorker-8] Task offer.tasks.req[8d93b335-f5c8-495e-8865-890f971a73fc] succeeded in 0.019374466000044777s: None
[2021-12-02 07:51:00,051: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:51:00,056: INFO/MainProcess] Received task: offer.tasks.req[57c89678-a51e-45de-a2d8-8db394fec865]  
[2021-12-02 07:51:00,079: INFO/ForkPoolWorker-8] Task offer.tasks.req[57c89678-a51e-45de-a2d8-8db394fec865] succeeded in 0.01969699000028413s: None
[2021-12-02 07:52:00,000: INFO/Beat] Scheduler: Sending due task pick-up-new-offer-every-60-seconds (offer.tasks.req)
[2021-12-02 07:52:00,006: INFO/MainProcess] Received task: offer.tasks.req[8df1fb7e-6125-4bfc-bd84-e76c37ed185a]  
[2021-12-02 07:52:00,029: INFO/ForkPoolWorker-8] Task offer.tasks.req[8df1fb7e-6125-4bfc-bd84-e76c37ed185a] succeeded in 0.019746381000004476s: None
[2021-12-02 07:52:15,433: INFO/MainProcess] beat: Shutting down...
